#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIRECTORY="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PYTHON_EXECUTABLE="$SCRIPT_DIRECTORY/../.venv/bin/python"
PREPARE_CONTEXT_SCRIPT="$SCRIPT_DIRECTORY/prepare_llm_context.py"
INVOKE_LLM_SCRIPT="$SCRIPT_DIRECTORY/invoke_llm.py"
PROCESS_RESPONSE_SCRIPT="$SCRIPT_DIRECTORY/process_llm_response.py"
RENDER_PDF_SCRIPT="$SCRIPT_DIRECTORY/render_report_pdf.py"

"$PYTHON_EXECUTABLE" "$PREPARE_CONTEXT_SCRIPT"
"$PYTHON_EXECUTABLE" "$INVOKE_LLM_SCRIPT"
"$PYTHON_EXECUTABLE" "$PROCESS_RESPONSE_SCRIPT"
"$PYTHON_EXECUTABLE" "$RENDER_PDF_SCRIPT"
